version: '3'
services:
  app:
    build: .
    container_name: todo-sql
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules